name: Release npm package

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance

jobs:
  release:
    name: Build & release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run prettier
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
      - run: npm run publint
      - run: npm run pack:check
      - name: semantic release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6
        with:
          semantic_version: 25
          extra_plugins: |
            conventional-changelog-conventionalcommits@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
